name: Code Linting on master branch

on:
  push:
    branches: [ master ]

jobs:
  build-test-ubuntu-with-thread-sanitizer-clang-latest:
    # prevent stuck jobs consuming runners for 3 hours
    timeout-minutes: 180
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install iceoryx dependencies and clang-tidy
        uses: ./.github/actions/install-iceoryx-deps-and-clang
      - name: Run Thread Sanitizer
        run: ./tools/ci/build-test-ubuntu-with-sanitizers.sh clang tsan
